"""Run the J language from Python and Jupyter through libj: sessions, magics and a Jupyter kernel.

`jlang.core` runs the [J language](https://www.jsoftware.com/) inside the Python process. It loads libj, J's engine library, from the J installation that this package contains. Install it with `pip install jlanguage` and import `J` from `jlang.core`. The module provides sessions and the `%%j` and `%j` magics; `jlang.kernel` provides the Jupyter kernel. Importing it does not start J.

The magics also need IPython.

Docs: https://answerdotai.github.io/jlanguage/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core.ipynb.

# %% auto #0
__all__ = ['J', 'JOut', 'JMagic', 'create_j_magic', 'load_ipython_extension', 'JError']

# %% ../../nbs/core.ipynb #9a091a86
from . import path, jconsole_path
from fastcore.utils import *
from ._engine import _J, JError

_all_ = ['JError']

# %% ../../nbs/core.ipynb #728a92a9
_LIBJ = 'j.dll' if sys.platform=='win32' else 'libj.dylib' if sys.platform=='darwin' else 'libj.so'

# %% ../../nbs/core.ipynb #c5bffe24
class J:
    "A J session: an engine from libj, with J's standard library loaded"
    def __init__(self, jbin=None): self._j = _J(Path(jbin or path()/'bin')/_LIBJ)

# %% ../../nbs/core.ipynb #11f64311
class JOut(str):
    "J's output, displayed as plain text"
    def __repr__(self): return str(self)

@patch
def run(self:J, code):
    "Run `code` (one or more lines of J), returning its output; raises `JError` on J errors"
    return self._j.run(code)

@patch
def __call__(self:J, code):
    "Run `code`, returning displayable output, or None if there is none"
    return JOut(self.run(code)) or None

# %% ../../nbs/core.ipynb #edd79864
def _nest(x, shape):
    "Nest flat sequence `x` (row-major ravel) into `shape`"
    if len(shape)<2: return x
    n = len(x)//shape[0] if shape[0] else 0
    return [_nest(x[i*n:(i+1)*n], shape[1:]) for i in range(shape[0])]

@patch
def getm(self:J, name):
    "Read noun `name` into Python: str for characters; int/float scalars and (nested) lists otherwise"
    shape,x = self._j.get(name)
    return _nest(x, shape) if shape or isinstance(x,str) else x[0]

# %% ../../nbs/core.ipynb #d8c04417
@patch
def pyval(self:J, expr):
    "Evaluate `expr` and return the result as a Python value"
    self.run(f'pytmp =: {expr}')
    try: return self.getm('pytmp')
    finally: self.run("4!:55 <'pytmp'")

@patch
def __getitem__(self:J, expr): return self.pyval(expr)

# %% ../../nbs/core.ipynb #a010ad8f
@patch
def __setitem__(self:J, nm, v):
    "Assign Python value `v` (scalar, string, or nested list) to noun `nm`"
    self._j.set(nm, v)

# %% ../../nbs/core.ipynb #b851b672
@patch
def fn(self:J, code):
    "A Python callable applying J verb `code` monadically or dyadically (left argument first)"
    def f(*args):
        if len(args)==1:
            self['pyy'] = args[0]
            return self.pyval(f'({code}) pyy')
        self['pyx'],self['pyy'] = args
        return self.pyval(f'pyx ({code}) pyy')
    return f

# %% ../../nbs/core.ipynb #0c583666
@patch
def interrupt(self:J):
    "Stop the running sentence with an attention interrupt; call it from another thread"
    self._j.interrupt()

# %% ../../nbs/core.ipynb #80c0283a
@patch
def close(self:J):
    "Free the engine; the session cannot run code afterwards"
    self._j.close()

@patch
def __enter__(self:J): return self

@patch
def __exit__(self:J, *args): self.close()

# %% ../../nbs/core.ipynb #5037ca61
@patch(as_prop=True)
def exited(self:J):
    "The exit code requested by `exit`, or None"
    return self._j.exited

# %% ../../nbs/core.ipynb #39cbb993
class JMagic:
    "IPython `%j`/`%%j` magics, driving a lazily-started `J` session"
    def __init__(self, jbin=None): self.jbin,self.o = jbin,None

    def j(self, line, cell=None):
        "Run J: a cell magic displays the session output; a line magic returns the expression's Python value"
        from IPython.display import display
        if not self.o: self.o = J(self.jbin)
        if cell is None: return self.o[line.strip()]
        disp,cell = True,cell.rstrip()
        if cell.endswith(';'): disp,cell = False,cell[:-1]
        out = self.o(cell)
        if disp and out: display(out)

# %% ../../nbs/core.ipynb #d95a4701
def create_j_magic(shell=None):
    "Create a `JMagic` and register its `j` line/cell magic with `shell`, returning it"
    from IPython import get_ipython
    shell = shell or get_ipython()
    jm = JMagic()
    shell.register_magic_function(jm.j, 'line_cell', 'j')
    return jm

def load_ipython_extension(ipython):
    "Register the `j` magics: `%load_ext jlang.core`"
    create_j_magic(shell=ipython)
